name: Linked issue policy

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  policy:
    uses: embeddedos-org/.github/.github/workflows/linked-issue-policy.yml@939db927f1de7d64b09cea9767fa7b8e7f78f6ca
    with:
      policy_ref: 92cb596c773496ec4df76717e8acf0e6b7700f73
